In [1]:
import pandas as pd
import numpy as np
#HI

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))


x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([ -8.19245986, -36.9777151 ,   3.81938056,  13.55796829,
       -18.34188975,   9.98168474,  -2.35160822,   1.35253975,
       -18.73549147, -20.07823742,  -6.91471924, -52.00503229,
       -16.18979919, -38.48747285,  31.78697295, -32.63355859,
       -24.52860393, -34.91515018, -42.81965235, -56.26352333,
        -0.6675883 ,   9.00083669,   7.03007167, -60.55491596,
       -40.02897782,  -8.38834034, -12.96983228, -38.83060617,
       -18.30833288, -32.8039111 ,   1.05972467,  13.09579972,
       -16.53160166, -54.76366408,   9.24059068, -10.50350059,
        -6.70291548,   3.23633947,   7.78482801,  -6.42379855,
        19.54745365, -44.24581072, -32.90593551,  -2.85986968,
       -30.91767751, -30.82845872,  21.22658356, -10.94488023,
       -38.89905431, -12.96544142])

In [5]:
x1

array([ 2, 16,  4, 13, 15,  7, 13, 19, 17, 16,  1,  6,  6,  7, 18,  8,  6,
        3, 11,  2, 12, 17,  8,  6, 16, 12,  6, 11,  7,  6,  9, 11, 10,  3,
       13,  1,  1,  8, 14, 13, 14,  4,  4,  7, 13,  9, 19, 17, 13, 12])

In [6]:
x2

array([ 4, 18,  2,  4, 13,  2,  8, 10, 14, 14,  3, 17,  8, 14,  2, 13, 10,
       11, 17, 16,  7,  7,  3, 19, 19,  9,  7, 16,  9, 12,  5,  3, 10, 16,
        5,  4,  3,  4,  6,  9,  3, 14, 11,  5, 15, 13,  5, 12, 17, 10])

In [16]:


x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1]) #weights or betas
print(x)
print(x.shape)
print(w.shape)

    intercept  x1  x2
0           1   2   4
1           1  16  18
2           1   4   2
3           1  13   4
4           1  15  13
5           1   7   2
6           1  13   8
7           1  19  10
8           1  17  14
9           1  16  14
10          1   1   3
11          1   6  17
12          1   6   8
13          1   7  14
14          1  18   2
15          1   8  13
16          1   6  10
17          1   3  11
18          1  11  17
19          1   2  16
20          1  12   7
21          1  17   7
22          1   8   3
23          1   6  19
24          1  16  19
25          1  12   9
26          1   6   7
27          1  11  16
28          1   7   9
29          1   6  12
30          1   9   5
31          1  11   3
32          1  10  10
33          1   3  16
34          1  13   5
35          1   1   4
36          1   1   3
37          1   8   4
38          1  14   6
39          1  13   9
40          1  14   3
41          1   4  14
42          1   4  11
43          1   7   5
44        

In [17]:
#calculating predicted y
#beta *x
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)  # function call

#myprediction(x,w).shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


(50,)

In [18]:
# calculating error
#yact - ypred
#yact - beta *X
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [19]:
# Calculating cost i.e error^2
# ((e*e.T))

def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)     #gives single error value 
    return(cost)

mycost(y,x,w)


36165.781724460336

In [20]:
# -(Error *X)
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([  769.75925263,  5409.49186276, 12401.43469411])

In [21]:
#pass various values of lr and check
#Gradient of beta_0 is small. Hence for small lr, change is small
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.000001)

35788.63640682334 [-0.0083814  -0.00540949 -0.01240143]
18485.462249716045 [-0.49482796 -0.20552629 -0.87620967]
13587.111603073703 [-0.63072988 -0.08269464 -1.34745833]
10635.460483958259 [-0.6536892   0.12336093 -1.67052591]
8402.001682726594 [-0.64041923  0.33758486 -1.92672199]
6649.823596222035 [-0.6156803   0.53783308 -2.14442993]
5268.399237296653 [-0.58745725  0.71881368 -2.33470422]
4178.506792538459 [-0.55831886  0.88046877 -2.50279222]
3318.485914415423 [-0.52908593  1.02424593 -2.6518784 ]
2639.784878421469 [-0.50001568  1.15191491 -2.78431446]
2104.1145120743613 [-0.47118408  1.26520383 -2.90203513]
1681.2727384188952 [-0.44260929  1.36569797 -3.00670907]
1347.4358247352532 [-0.41429139  1.45482162 -3.09980225]
1083.8112640224185 [-0.38622517  1.533845   -3.1826115 ]
875.575233197299 [-0.35840422  1.60389796 -3.25628693]
711.0344561111318 [-0.33082212  1.66598452 -3.32184948]
580.9650717991235 [-0.30347288  1.72099657 -3.38020574]
478.0911256701538 [-0.27635096  1.76972629

18.895123577076653 [ 1.99450065  2.06280739 -3.93612737]
18.690819034025342 [ 2.00487387  2.0623337  -3.93658869]
18.48943842208413 [ 2.0151726   2.06186342 -3.93704669]
18.29093989503157 [ 2.02539737  2.06139651 -3.93750141]
18.095282205533785 [ 2.0355487   2.06093295 -3.93795285]
17.902424696573714 [ 2.04562714  2.06047272 -3.93840106]
17.712327293002367 [ 2.05563319  2.0600158  -3.93884605]
17.524950493211506 [ 2.06556739  2.05956216 -3.93928784]
17.340255360925354 [ 2.07543024  2.05911177 -3.93972645]
17.158203517109623 [ 2.08522226  2.05866462 -3.94016192]
16.97875713199668 [ 2.09494396  2.05822068 -3.94059426]
16.801878917224542 [ 2.10459584  2.05777993 -3.94102349]
16.6275321180885 [ 2.11417841  2.05734234 -3.94144964]
16.455680505903548 [ 2.12369215  2.0569079  -3.94187273]
16.286288370476225 [ 2.13313758  2.05647657 -3.94229278]
16.11932051268423 [ 2.14251517  2.05604835 -3.94270982]
15.954742237162105 [ 2.15182541  2.05562319 -3.94312386]
15.792519345091495 [ 2.16106879  2.05

6.334903327367121 [ 2.93824265  2.01971136 -3.97809681]
6.310356014304368 [ 2.9418383   2.01954717 -3.97825671]
6.286160013313522 [ 2.94540812  2.01938415 -3.97841547]
6.2623102965460555 [ 2.94895231  2.01922231 -3.97857308]
6.238801908110179 [ 2.95247104  2.01906162 -3.97872956]
6.215629963040984 [ 2.9559645   2.01890209 -3.97888492]
6.192789646285304 [ 2.95943287  2.01874371 -3.97903917]
6.170276211701311 [ 2.96287634  2.01858646 -3.9791923 ]
6.148084981072185 [ 2.96629507  2.01843035 -3.97934434]
6.126211343133988 [ 2.96968926  2.01827535 -3.97949528]
6.104650752617506 [ 2.97305906  2.01812147 -3.97964514]
6.083398729303741 [ 2.97640467  2.01796869 -3.97979392]
6.062450857092983 [ 2.97972625  2.01781701 -3.97994164]
6.041802783087013 [ 2.98302398  2.01766642 -3.98008829]
6.021450216684713 [ 2.98629802  2.01751691 -3.98023389]
6.001388928690558 [ 2.98954855  2.01736847 -3.98037845]
5.981614750435518 [ 2.99277574  2.0172211  -3.98052196]
5.962123572911198 [ 2.99597975  2.01707479 -3.9

4.819928812476187 [ 3.2678533   2.00465965 -3.992755  ]
4.817063254739651 [ 3.26908181  2.00460355 -3.99280964]
4.814238707806319 [ 3.2703015   2.00454786 -3.99286388]
4.811454584744738 [ 3.27151243  2.00449256 -3.99291773]
4.8087103070234445 [ 3.27271466  2.00443766 -3.99297119]
4.806005304390576 [ 3.27390826  2.00438315 -3.99302427]
4.803339014755652 [ 3.27509329  2.00432904 -3.99307697]
4.800710884072527 [ 3.27626981  2.00427531 -3.99312929]
4.798120366224381 [ 3.27743788  2.00422197 -3.99318124]
4.795566922910252 [ 3.27859756  2.00416901 -3.99323281]
4.7930500235330555 [ 3.27974891  2.00411644 -3.99328401]
4.790569145089519 [ 3.28089199  2.00406424 -3.99333485]
4.788123772061324 [ 3.28202686  2.00401242 -3.99338532]
4.785713396308153 [ 3.28315359  2.00396096 -3.99343542]
4.783337516961856 [ 3.28427222  2.00390988 -3.99348517]
4.780995640322656 [ 3.28538281  2.00385917 -3.99353456]
4.778687279756357 [ 3.28648544  2.00380881 -3.9935836 ]
4.7764119555933195 [ 3.28758014  2.00375882 -3

4.64376025659338 [ 3.37962165  1.99955574 -3.99772548]
4.643415958117139 [ 3.38004749  1.99953629 -3.99774442]
4.643076587113455 [ 3.38047027  1.99951698 -3.99776322]
4.642742073062132 [ 3.38089001  1.99949782 -3.99778188]
4.642412346452273 [ 3.38130674  1.99947879 -3.99780042]
4.642087338767816 [ 3.38172047  1.99945989 -3.99781882]
4.641766982473193 [ 3.38213123  1.99944114 -3.99783708]
4.64145121099946 [ 3.38253905  1.99942251 -3.99785522]
4.6411399587303555 [ 3.38294393  1.99940402 -3.99787322]
4.6408331609886755 [ 3.38334591  1.99938567 -3.9978911 ]
4.640530754022904 [ 3.383745    1.99936744 -3.99790885]
4.640232674993836 [ 3.38414122  1.99934935 -3.99792647]
4.639938861961685 [ 3.3845346   1.99933139 -3.99794396]
4.639649253873058 [ 3.38492515  1.99931355 -3.99796133]
4.639363790548329 [ 3.3853129   1.99929585 -3.99797858]
4.639082412669214 [ 3.38569787  1.99927827 -3.99799569]
4.638805061766314 [ 3.38608006  1.99926081 -3.99801269]
4.6385316802070164 [ 3.38645952  1.99924348 -3.9

4.622552131551796 [ 3.41851124  1.99777984 -3.99945495]
4.622511355922688 [ 3.41865779  1.99777315 -3.99946146]
4.622471163859325 [ 3.41880328  1.9977665  -3.99946793]
4.62243154700991 [ 3.41894773  1.99775991 -3.99947436]
4.622392497142184 [ 3.41909114  1.99775336 -3.99948074]
4.622354006141741 [ 3.41923352  1.99774686 -3.99948707]
4.622316066010297 [ 3.41937488  1.9977404  -3.99949335]
4.622278668863972 [ 3.41951523  1.99773399 -3.99949959]
4.622241806931783 [ 3.41965456  1.99772763 -3.99950579]
4.622205472553933 [ 3.4197929   1.99772131 -3.99951194]
4.622169658180276 [ 3.41993024  1.99771504 -3.99951805]
4.622134356368723 [ 3.4200666   1.99770881 -3.99952411]
4.622099559783614 [ 3.42020197  1.99770263 -3.99953014]
4.62206526119439 [ 3.42033638  1.99769649 -3.99953611]
4.622031453473902 [ 3.42046982  1.9976904  -3.99954205]
4.621998129597 [ 3.4206023   1.99768435 -3.99954794]
4.6219652826391044 [ 3.42073383  1.99767834 -3.99955379]
4.62193290577473 [ 3.42086441  1.99767238 -3.9995595

4.6200356019925 [ 3.43194506  1.99716638 -4.00005236]
4.620030842004337 [ 3.43199513  1.9971641  -4.00005459]
4.62002615013937 [ 3.43204484  1.99716183 -4.0000568 ]
4.620021525422656 [ 3.4320942   1.99715957 -4.000059  ]
4.620016966893153 [ 3.4321432   1.99715733 -4.00006118]
4.62001247360365 [ 3.43219184  1.99715511 -4.00006334]
4.620008044620462 [ 3.43224014  1.99715291 -4.00006549]
4.620003679023217 [ 3.43228809  1.99715072 -4.00006762]
4.619999375904797 [ 3.4323357   1.99714854 -4.00006974]
4.619995134371037 [ 3.43238296  1.99714639 -4.00007184]
4.619990953540503 [ 3.43242989  1.99714424 -4.00007393]
4.619986832544492 [ 3.43247648  1.99714211 -4.000076  ]
4.619982770526656 [ 3.43252273  1.99714    -4.00007805]
4.619978766642919 [ 3.43256865  1.99713791 -4.0000801 ]
4.61997482006128 [ 3.43261424  1.99713582 -4.00008212]
4.619970929961651 [ 3.43265951  1.99713376 -4.00008414]
4.619967095535711 [ 3.43270445  1.9971317  -4.00008614]
4.619963315986631 [ 3.43274906  1.99712967 -4.0000881

array([ 3.43580671,  1.99699004, -4.0002241 ])

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
lr=LinearRegression()

In [24]:
x.shape

(50, 3)

In [25]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [31]:
lr.coef_

array([ 2.00346005, -4.01022363])

In [32]:
lr.intercept_

3.530674802067832

In [ ]:
lr.fit()